In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score, classification_report
import xgboost as xgb

In [3]:
df = pd.read_csv("/content/ott_movies_clean_unique.csv")

In [4]:
df.head()

  content_id  ...                       poster_url
0    C100146  ...  https://via.placeholder.com/150
1    C100452  ...  https://via.placeholder.com/150
2    C101169  ...  https://via.placeholder.com/150
3    C100271  ...  https://via.placeholder.com/150
4    C100591  ...  https://via.placeholder.com/150

[5 rows x 19 columns]

In [6]:
df.shape

(2500, 19)

In [7]:
df.isna().sum()

content_id           0
title                0
type                 0
genre                0
platform             0
country              0
language             0
release_year         0
duration_minutes     0
rating               0
votes                0
weighted_rating      0
engagement_score     0
popularity_score     0
trending_score       0
tags                 0
combined_features    0
description          0
poster_url           0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   content_id         2500 non-null   object
 1   title              2500 non-null   object
 2   type               2500 non-null   object
 3   genre              2500 non-null   object
 4   platform           2500 non-null   object
 5   country            2500 non-null   object
 6   language           2500 non-null   object
 7   release_year       2500 non-null   int64
 8   duration_minutes   2500 non-null   int64
 9   rating             2500 non-null   float64
 10  votes              2500 non-null   int64
 11  weighted_rating    2500 non-null   float64
 12  engagement_score   2500 non-null   float64
 13  popularity_score   2500 non-null   float64
 14  trending_score     2500 non-null   float64
 15  tags               2500 non-null   object
 16  combined_features  2500 non-null   object
 17  description        2500 non-null   object
 18  poster_url         2500 non-null   object
dtypes: float64(5), int64(3), object(11)
memory usage: 371.2+ KB

In [12]:
df.describe()

       release_year  duration_minutes  ...  popularity_score  trending_score
count   2500.000000       2500.000000  ...       2500.000000     2500.000000
mean    2019.578800        634.919600  ...        747.735336      747.113316
std        2.861864        617.055317  ...        441.421568      451.923130
min     2015.000000         80.000000  ...          3.690000        3.300000
25%     2017.000000        128.000000  ...        382.855000      377.722500
50%     2020.000000        302.000000  ...        734.675000      727.615000
75%     2022.000000       1116.000000  ...       1096.752500     1076.977500
max     2024.000000       2000.000000  ...       1872.710000     2198.940000

[8 rows x 8 columns]

##EDA

In [15]:
df.head()

  content_id  ...                       poster_url
0    C100146  ...  https://via.placeholder.com/150
1    C100452  ...  https://via.placeholder.com/150
2    C101169  ...  https://via.placeholder.com/150
3    C100271  ...  https://via.placeholder.com/150
4    C100591  ...  https://via.placeholder.com/150

[5 rows x 19 columns]

In [17]:
cols = ['genre','platform','country','language']

for col in cols:
  plt.figure(figsize=(12,9))
  fig = px.bar(df,x=col,title=f"Count plot of {col}")

  fig.show()

In [35]:
cols = ['genre','platform','country','language']

for col in cols:
    count = df[col].value_counts()
    top_name = count.idxmax()
    top_count = count.max()

    print(col,'->',top_name,top_count)

genre -> Drama 374
platform -> Prime Video 852
country -> India 455
language -> German 530

In [36]:
df.head()

  content_id  ...                       poster_url
0    C100146  ...  https://via.placeholder.com/150
1    C100452  ...  https://via.placeholder.com/150
2    C101169  ...  https://via.placeholder.com/150
3    C100271  ...  https://via.placeholder.com/150
4    C100591  ...  https://via.placeholder.com/150

[5 rows x 19 columns]

In [42]:
count = df['genre'].value_counts().reset_index()
count.columns = ['genre', 'count']

fig = px.pie(count, names='genre', values='count', title='Genre Distribution')
fig.show()

In [49]:
count_plat = df.groupby(['platform','release_year']).size().reset_index(name='movie_count')
count_plat

       platform  release_year  movie_count
0       Hotstar          2015           76
1       Hotstar          2016           74
2       Hotstar          2017           74
3       Hotstar          2018           82
4       Hotstar          2019           93
5       Hotstar          2020           86
6       Hotstar          2021           96
7       Hotstar          2022           69
8       Hotstar          2023           98
9       Hotstar          2024           76
10      Netflix          2015           81
11      Netflix          2016           69
12      Netflix          2017           86
13      Netflix          2018           84
14      Netflix          2019           87
15      Netflix          2020           78
16      Netflix          2021           90
17      Netflix          2022           80
18      Netflix          2023           73
19      Netflix          2024           96
20  Prime Video          2015           76
21  Prime Video          2016           93
22  Prime Video          2017           87
23  Prime Video          2018           91
24  Prime Video          2019           78
25  Prime Video          2020           88
26  Prime Video          2021           71
27  Prime Video          2022           91
28  Prime Video          2023           77
29  Prime Video          2024          100

In [50]:
df['genre']

0          Drama
1         Action
2       Thriller
3         Sci-Fi
4          Drama
          ...
2495      Sci-Fi
2496      Sci-Fi
2497      Sci-Fi
2498      Comedy
2499    Thriller
Name: genre, Length: 2500, dtype: object

In [54]:
avg_rating = df.groupby('genre')['rating'].mean().reset_index()
avg_rating

      genre    rating
0    Action  7.523944
1    Comedy  7.477493
2     Crime  7.476294
3     Drama  7.487701
4   Fantasy  7.490286
5    Sci-Fi  7.515946
6  Thriller  7.434234

In [55]:
fig = px.bar(
    avg_rating,
    x='genre',
    y='rating',
    title='Average Rating by Genre',
    text_auto=True
)

fig.update_layout(xaxis_title='Genre', yaxis_title='Avg Rating')
fig.show()

In [58]:
count_df = df.groupby(['platform', 'type']).size().reset_index(name='count')
count_df

      platform    type  count
0      Hotstar   Movie    420
1      Hotstar  Series    404
2      Netflix   Movie    415
3      Netflix  Series    409
4  Prime Video   Movie    411
5  Prime Video  Series    441

In [59]:
fig = px.bar(
    count_df,
    x='platform',
    y='count',
    color='type',
    barmode='group',
    text='count',
    title='Movies vs Series by Platform'
)

fig.update_layout(
    xaxis_title='Platform',
    yaxis_title='Number of Titles'
)

fig.show()

In [60]:
target = 'rating'

X = df.drop(columns=['rating', 'title', 'description', 'poster_url', 'content_id'])
y = df[target]

In [61]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

In [62]:
cat_cols = X.select_dtypes(include='object').columns
num_cols = X.select_dtypes(exclude='object').columns

preprocessor = ColumnTransformer([
    ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols),
    ('num', 'passthrough', num_cols)
])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [64]:
from xgboost import XGBRegressor

rf = RandomForestRegressor(n_estimators=200, random_state=42)
xgb = XGBRegressor(n_estimators=300, learning_rate=0.1, random_state=42)

In [65]:
rf_pipeline = Pipeline([
    ('prep', preprocessor),
    ('model', rf)
])

xgb_pipeline = Pipeline([
    ('prep', preprocessor),
    ('model', xgb)
])

rf_pipeline.fit(X_train, y_train)
xgb_pipeline.fit(X_train, y_train)

Pipeline(steps=[('prep',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['type', 'genre', 'platform', 'country', 'language', 'tags',
       'combined_features'],
      dtype='object')),
                                                 ('num', 'passthrough',
                                                  Index(['release_year', 'duration_minutes', 'votes', 'weighted_rating',
       'engagement_score', 'popularity_score', 'trending_score'],
      dtype...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.1,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=None, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=300, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [68]:
from sklearn.metrics import mean_squared_error
import numpy as np

rf_rmse = np.sqrt(mean_squared_error(y_test, rf_pred))
xgb_rmse = np.sqrt(mean_squared_error(y_test, xgb_pred))

print("RF RMSE:", rf_rmse)
print("XGB RMSE:", xgb_rmse)

RF RMSE: 0.062049903303712024
XGB RMSE: 0.0627530566657403

In [73]:
from sklearn.metrics import r2_score

print("RF R2:", r2_score(y_test, rf_pred))
print("XGB R2:", r2_score(y_test, xgb_pred))

RF R2: 0.9959876922034817
XGB R2: 0.995896241517626

In [ ]:
# Random Forest Model Performs Better
#acheive R2 score = 0.9959 and RMSE = 0.0620